### PR TITLE
SvelteKit Support

### LINKED ISSUE #59: Does not work with latest Sveltekit anymore
In the latest sveltekit, there seem to have been several changes. There is no client.js or server.js anymore. Also, the svelte config is different and snowpack has been replaced by vite.

### PR DESCRIPTION
**Pull request by AlecAivazis**
This PR adds support for the most recent public beta of Sveltekit. This required updating a few things:

* the query loader API dramatically changed so the preprocessor has to support two different targets 
* the target location when generating the runtime for a sveltekit project should point to the project root
* a new kit adapter
* bundle and publish esm and cjs versions of `houdini-preprocess` and generated runtime

closes #59, #66

### CODE REVIEW

**Comment by pixelmund** [comment]
Nice was waiting for it, LGTM!

**Comment by AlecAivazis** [comment]
Going through the exercise of updating the example has brought up some more things that need updating. I'll keep this PR open for visibility while I get it updated. Thanks for being patient!

**Comment by AlecAivazis** [comment]
Still cranking on this in my downtime. I recently started a new job which has taken my attention the majority of my attention for the past few weeks but I feel like I"m at the final mile for this integration.

I really appreciate everyone's patience!

**Comment by AlecAivazis** [comment]
@pixelmund - do you mind pulling this down and making sure that the example directory works as expected?

**Comment by pixelmund** [comment]
> @pixelmund - do you mind pulling this down and making sure that the example directory works as expected? I think this might actually be ready to get merged in 🎉

Hey, sorry don't have much time because of work right now. I can try to pull it later today or tomorrow.

**Comment by pixelmund** [comment]
I've pulled it and tested some stuff it's working as far as i can tell, we should probably update the SvelteKit Version currently using `1.0.0-next.75`, latest is `1.0.0-next.105`, there where some changes with the config. It should now be `svelte.config.js` and `esm` instead of `cjs`. 

One thing i have noticed is the `AllItemsVariables function` calls `this.error`, when i go to a route/filter that does not exist lets say `/foo` i get the following error.

```bash
TypeError: this.error is not a function
    at AllItemsVariables ([filter].svelte:16:18)
    at RequestContext.computeInput (/$houdini/runtime/network.js:87:20)
    at load ([filter].svelte:27:57)
    at load_node (file:///Users/js/dev/houdini/node_modules/@sveltejs/kit/dist/ssr.js:2457:30)
    at respond (file:///Users/js/dev/houdini/node_modules/@sveltejs/kit/dist/ssr.js:2670:21)
    at async render_page (file:///Users/js/dev/houdini/node_modules/@sveltejs/kit/dist/ssr.js:2807:20)
    at async render (file:///Users/js/dev/houdini/node_modules/@sveltejs/kit/dist/ssr.js:2934:10)
    at async ssr (file:///Users/js/dev/houdini/node_modules/@sveltejs/kit/dist/ssr.js:2921:10)
    at async Immediate.<anonymous> (file:///Users/js/dev/houdini/node_modules/@sveltejs/kit/dist/chunks/index2.js:3302:23)
```

**Comment by AlecAivazis** [comment]
Thanks for finding the time to try it out @pixelmund! I'll work through the issues you ran into in the next few days.

To answer your question, houdini doesn't yet support resolving requests from the cache. it currently only uses it as an orchestration mechanism for mutations to update the state of queries that are current mounted. I felt like that was a reasonable "first step" towards saving network requests and then got distracted with the sveltekit support before I could get to it.

**Comment by pixelmund** [comment]
> Thanks for finding the time to try it out @pixelmund! I'll work through the issues you ran into in the next few days.
> 
> To answer your question, houdini doesn't yet support resolving requests from the cache. it currently only uses it as an orchestration mechanism for mutations to update the state of queries that are current mounted. I felt like that was a reasonable "first step" towards saving network requests and then got distracted with the sveltekit support before I could get to it.

Alright good to know, well maybe you could publish the kit version under a next flag like kit does or something so people can try it out already and report upcoming issues, don't know how that is working but would be cool.

**Comment by AlecAivazis** [comment]
Okay, this branch now supports the sapper and sveltekit versions of the example application. I'm only going to leave the sveltekit version in the repo but at least I have seen sapper support work with the changes in this branch.

I think this branch is very close to being merged. Going to keep poking at it for a few more days but im hopeful

**Comment by AlecAivazis** [comment]
Alright, yall! SvelteKit support is finally released in version `0.5.0`. *Please* feel free to open a ticket if you run into any problems.

**Pull request merged**
