### PR TITLE
fixes single-quoted attribute values not being parsed

### PR DESCRIPTION
**Pull request by outerlook**

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Thanks @outerlook! Mind putting together a quick test that verifies this behavior? If someone refactors this function, i worried they might forget about this subtlety - I know i would 😅

**Comment by outerlook** [comment]
Sure!

**Comment by AlecAivazis** [comment]
@outerlook any updates? If you dont have the time I can see this PR through - just let me know 😄

**Comment by AlecAivazis** [comment]
I'm going to close this and open another PR from a branch local to this repo to add some tests. Thanks for the quick fix @outerlook !

**Pull request closed without merging**
